version: '3.4'

services:
    challenge:
        restart: always        
        build:
            context: .
        container_name: misc_prisonbreak1-2
        ports:
            - 5000:5000
